import {icon} from "./icons.js";

export function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");}
export function initials(v){return String(v||"User").trim().split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()||"").join("")||"U";}
export function avatar(person={},size="md",polygon=false){const name=esc(person.displayName||person.username||"User");const url=esc(person.photoURL||person.photoUrl||"");return `<div class="avatar avatar-${size}${polygon?" avatar-polygon":""}" title="${name}">${url?`<img src="${url}" alt="${name}" loading="lazy">`:`<span>${initials(person.displayName||person.username)}</span>`}</div>`;}
export function when(v){if(!v)return "";const d=v?.toDate?v.toDate():new Date(v);if(Number.isNaN(d.getTime()))return "";const n=Math.max(0,Math.floor((Date.now()-d.getTime())/1000));if(n<45)return "now";if(n<3600)return `${Math.floor(n/60)}m`;if(n<86400)return `${Math.floor(n/3600)}h`;if(n<604800)return `${Math.floor(n/86400)}d`;return d.toLocaleDateString([],{day:"numeric",month:"short"});}
export function formatDate(v){if(!v)return "";const d=v?.toDate?v.toDate():new Date(v);return Number.isNaN(d.getTime())?"":d.toLocaleString([],{day:"numeric",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"});}
export function toast(message,kind="info"){const root=document.getElementById("toast-root");if(!root)return;const n=document.createElement("div");n.className=`toast toast-${kind}`;n.textContent=message;root.appendChild(n);setTimeout(()=>n.remove(),3600);}
export function modal(title,body,actions="",opts={}){document.getElementById("modal-root").innerHTML=`<div class="modal-backdrop" data-action="close-modal"><section class="modal${opts.narrow?" modal-narrow":""}${opts.wide?" modal-wide":""}" role="dialog" aria-modal="true" aria-label="${esc(title)}"><header class="modal-head"><div><span class="eyebrow">MARVEL CHAT</span><h2>${esc(title)}</h2></div><button class="icon-btn" data-action="close-modal" aria-label="Close">${icon("close",20)}</button></header><div class="modal-body">${body}</div>${actions?`<footer class="modal-actions">${actions}</footer>`:""}</section></div>`;}
export function closeModal(){document.getElementById("modal-root").innerHTML="";}
export function friendlyError(error){const code=String(error?.code||"").toLowerCase();const msg=String(error?.message||"").toLowerCase();if(code.includes("auth/invalid-credential")||code.includes("auth/invalid-login-credentials")||code.includes("auth/wrong-password"))return "We couldn't sign you in with those details.";if(code.includes("auth/user-not-found"))return "We couldn't find an account with that email.";if(code.includes("auth/email-already-in-use"))return "That email is already connected to an account.";if(code.includes("auth/weak-password"))return "Choose a stronger password to continue.";if(code.includes("auth/invalid-email"))return "Enter a valid email address.";if(code.includes("auth/popup-closed-by-user"))return "The Google sign-in window was closed.";if(code.includes("auth/unauthorized-domain"))return "Sign-in is not available from this address yet.";if(code.includes("app-check")||msg.includes("app check"))return "This action is temporarily unavailable. Please try again shortly.";if(msg.includes("permission")||msg.includes("permission-denied"))return "We couldn't complete that action right now.";if(msg.includes("network"))return "Please check your connection and try again.";if(code.includes("resource-exhausted")||msg.includes("quota"))return "This action is busy right now. Please try again shortly.";if(code.includes("failed-precondition"))return "This action is not available right now.";return "Something went wrong. Please try again.";}
